// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protos/proposal.proto

package protos

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ProposalStatus int32

const (
	ProposalStatus_VOTING   ProposalStatus = 0
	ProposalStatus_SUCCESS  ProposalStatus = 1
	ProposalStatus_FAILURE  ProposalStatus = 2
	ProposalStatus_CANCELED ProposalStatus = 3
)

var ProposalStatus_name = map[int32]string{
	0: "VOTING",
	1: "SUCCESS",
	2: "FAILURE",
	3: "CANCELED",
}

var ProposalStatus_value = map[string]int32{
	"VOTING":   0,
	"SUCCESS":  1,
	"FAILURE":  2,
	"CANCELED": 3,
}

func (x ProposalStatus) String() string {
	return proto.EnumName(ProposalStatus_name, int32(x))
}

func (ProposalStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_98cf7ef12ed80c79, []int{0}
}

// GovernTokenBalance
type GovernTokenBalance struct {
	TotalBalance                string   `protobuf:"bytes,1,opt,name=total_balance,json=totalBalance,proto3" json:"total_balance,omitempty"`
	AvailableBalanceForTdpos    string   `protobuf:"bytes,2,opt,name=available_balance_for_tdpos,json=availableBalanceForTdpos,proto3" json:"available_balance_for_tdpos,omitempty"`
	LockedBalanceForTdpos       string   `protobuf:"bytes,3,opt,name=locked_balance_for_tdpos,json=lockedBalanceForTdpos,proto3" json:"locked_balance_for_tdpos,omitempty"`
	AvailableBalanceForProposal string   `protobuf:"bytes,4,opt,name=available_balance_for_proposal,json=availableBalanceForProposal,proto3" json:"available_balance_for_proposal,omitempty"`
	LockedBalanceForProposal    string   `protobuf:"bytes,5,opt,name=locked_balance_for_proposal,json=lockedBalanceForProposal,proto3" json:"locked_balance_for_proposal,omitempty"`
	XXX_NoUnkeyedLiteral        struct{} `json:"-"`
	XXX_unrecognized            []byte   `json:"-"`
	XXX_sizecache               int32    `json:"-"`
}

func (m *GovernTokenBalance) Reset()         { *m = GovernTokenBalance{} }
func (m *GovernTokenBalance) String() string { return proto.CompactTextString(m) }
func (*GovernTokenBalance) ProtoMessage()    {}
func (*GovernTokenBalance) Descriptor() ([]byte, []int) {
	return fileDescriptor_98cf7ef12ed80c79, []int{0}
}

func (m *GovernTokenBalance) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GovernTokenBalance.Unmarshal(m, b)
}
func (m *GovernTokenBalance) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GovernTokenBalance.Marshal(b, m, deterministic)
}
func (m *GovernTokenBalance) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GovernTokenBalance.Merge(m, src)
}
func (m *GovernTokenBalance) XXX_Size() int {
	return xxx_messageInfo_GovernTokenBalance.Size(m)
}
func (m *GovernTokenBalance) XXX_DiscardUnknown() {
	xxx_messageInfo_GovernTokenBalance.DiscardUnknown(m)
}

var xxx_messageInfo_GovernTokenBalance proto.InternalMessageInfo

func (m *GovernTokenBalance) GetTotalBalance() string {
	if m != nil {
		return m.TotalBalance
	}
	return ""
}

func (m *GovernTokenBalance) GetAvailableBalanceForTdpos() string {
	if m != nil {
		return m.AvailableBalanceForTdpos
	}
	return ""
}

func (m *GovernTokenBalance) GetLockedBalanceForTdpos() string {
	if m != nil {
		return m.LockedBalanceForTdpos
	}
	return ""
}

func (m *GovernTokenBalance) GetAvailableBalanceForProposal() string {
	if m != nil {
		return m.AvailableBalanceForProposal
	}
	return ""
}

func (m *GovernTokenBalance) GetLockedBalanceForProposal() string {
	if m != nil {
		return m.LockedBalanceForProposal
	}
	return ""
}

// TriggerDesc
type TriggerDesc struct {
	Height               int64             `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	Module               string            `protobuf:"bytes,2,opt,name=module,proto3" json:"module,omitempty"`
	Method               string            `protobuf:"bytes,3,opt,name=method,proto3" json:"method,omitempty"`
	Args                 map[string][]byte `protobuf:"bytes,4,rep,name=args,proto3" json:"args,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *TriggerDesc) Reset()         { *m = TriggerDesc{} }
func (m *TriggerDesc) String() string { return proto.CompactTextString(m) }
func (*TriggerDesc) ProtoMessage()    {}
func (*TriggerDesc) Descriptor() ([]byte, []int) {
	return fileDescriptor_98cf7ef12ed80c79, []int{1}
}

func (m *TriggerDesc) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TriggerDesc.Unmarshal(m, b)
}
func (m *TriggerDesc) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TriggerDesc.Marshal(b, m, deterministic)
}
func (m *TriggerDesc) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TriggerDesc.Merge(m, src)
}
func (m *TriggerDesc) XXX_Size() int {
	return xxx_messageInfo_TriggerDesc.Size(m)
}
func (m *TriggerDesc) XXX_DiscardUnknown() {
	xxx_messageInfo_TriggerDesc.DiscardUnknown(m)
}

var xxx_messageInfo_TriggerDesc proto.InternalMessageInfo

func (m *TriggerDesc) GetHeight() int64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *TriggerDesc) GetModule() string {
	if m != nil {
		return m.Module
	}
	return ""
}

func (m *TriggerDesc) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *TriggerDesc) GetArgs() map[string][]byte {
	if m != nil {
		return m.Args
	}
	return nil
}

// Proposal
type Proposal struct {
	Module               string            `protobuf:"bytes,1,opt,name=module,proto3" json:"module,omitempty"`
	Method               string            `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	Args                 map[string][]byte `protobuf:"bytes,3,rep,name=args,proto3" json:"args,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Trigger              *TriggerDesc      `protobuf:"bytes,4,opt,name=trigger,proto3" json:"trigger,omitempty"`
	VoteAmount           string            `protobuf:"bytes,5,opt,name=vote_amount,json=voteAmount,proto3" json:"vote_amount,omitempty"`
	Status               ProposalStatus    `protobuf:"varint,6,opt,name=status,proto3,enum=protos.ProposalStatus" json:"status,omitempty"`
	Proposer             string            `protobuf:"bytes,7,opt,name=proposer,proto3" json:"proposer,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Proposal) Reset()         { *m = Proposal{} }
func (m *Proposal) String() string { return proto.CompactTextString(m) }
func (*Proposal) ProtoMessage()    {}
func (*Proposal) Descriptor() ([]byte, []int) {
	return fileDescriptor_98cf7ef12ed80c79, []int{2}
}

func (m *Proposal) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Proposal.Unmarshal(m, b)
}
func (m *Proposal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Proposal.Marshal(b, m, deterministic)
}
func (m *Proposal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Proposal.Merge(m, src)
}
func (m *Proposal) XXX_Size() int {
	return xxx_messageInfo_Proposal.Size(m)
}
func (m *Proposal) XXX_DiscardUnknown() {
	xxx_messageInfo_Proposal.DiscardUnknown(m)
}

var xxx_messageInfo_Proposal proto.InternalMessageInfo

func (m *Proposal) GetModule() string {
	if m != nil {
		return m.Module
	}
	return ""
}

func (m *Proposal) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *Proposal) GetArgs() map[string][]byte {
	if m != nil {
		return m.Args
	}
	return nil
}

func (m *Proposal) GetTrigger() *TriggerDesc {
	if m != nil {
		return m.Trigger
	}
	return nil
}

func (m *Proposal) GetVoteAmount() string {
	if m != nil {
		return m.VoteAmount
	}
	return ""
}

func (m *Proposal) GetStatus() ProposalStatus {
	if m != nil {
		return m.Status
	}
	return ProposalStatus_VOTING
}

func (m *Proposal) GetProposer() string {
	if m != nil {
		return m.Proposer
	}
	return ""
}

type ProposalRatio struct {
	UserRatio            map[string]int64 `protobuf:"bytes,1,rep,name=user_ratio,json=userRatio,proto3" json:"user_ratio,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ProposalRatio) Reset()         { *m = ProposalRatio{} }
func (m *ProposalRatio) String() string { return proto.CompactTextString(m) }
func (*ProposalRatio) ProtoMessage()    {}
func (*ProposalRatio) Descriptor() ([]byte, []int) {
	return fileDescriptor_98cf7ef12ed80c79, []int{3}
}

func (m *ProposalRatio) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProposalRatio.Unmarshal(m, b)
}
func (m *ProposalRatio) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProposalRatio.Marshal(b, m, deterministic)
}
func (m *ProposalRatio) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProposalRatio.Merge(m, src)
}
func (m *ProposalRatio) XXX_Size() int {
	return xxx_messageInfo_ProposalRatio.Size(m)
}
func (m *ProposalRatio) XXX_DiscardUnknown() {
	xxx_messageInfo_ProposalRatio.DiscardUnknown(m)
}

var xxx_messageInfo_ProposalRatio proto.InternalMessageInfo

func (m *ProposalRatio) GetUserRatio() map[string]int64 {
	if m != nil {
		return m.UserRatio
	}
	return nil
}

//冻结资产记录表
type FrozenAssetsTable struct {
	Total string `protobuf:"bytes,1,opt,name=total,proto3" json:"total,omitempty"`
	//repeated FrozenDetails  frozendetail = 2;
	FrozenDetail map[string]*FrozenDetails `protobuf:"bytes,2,rep,name=frozen_detail,json=frozenDetail,proto3" json:"frozen_detail,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	//repeated FrozenDetails  thawdetail = 3;
	ThawDetail           map[string]*FrozenDetails `protobuf:"bytes,3,rep,name=thaw_detail,json=thawDetail,proto3" json:"thaw_detail,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Timestamp            int64                     `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *FrozenAssetsTable) Reset()         { *m = FrozenAssetsTable{} }
func (m *FrozenAssetsTable) String() string { return proto.CompactTextString(m) }
func (*FrozenAssetsTable) ProtoMessage()    {}
func (*FrozenAssetsTable) Descriptor() ([]byte, []int) {
	return fileDescriptor_98cf7ef12ed80c79, []int{4}
}

func (m *FrozenAssetsTable) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FrozenAssetsTable.Unmarshal(m, b)
}
func (m *FrozenAssetsTable) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FrozenAssetsTable.Marshal(b, m, deterministic)
}
func (m *FrozenAssetsTable) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FrozenAssetsTable.Merge(m, src)
}
func (m *FrozenAssetsTable) XXX_Size() int {
	return xxx_messageInfo_FrozenAssetsTable.Size(m)
}
func (m *FrozenAssetsTable) XXX_DiscardUnknown() {
	xxx_messageInfo_FrozenAssetsTable.DiscardUnknown(m)
}

var xxx_messageInfo_FrozenAssetsTable proto.InternalMessageInfo

func (m *FrozenAssetsTable) GetTotal() string {
	if m != nil {
		return m.Total
	}
	return ""
}

func (m *FrozenAssetsTable) GetFrozenDetail() map[string]*FrozenDetails {
	if m != nil {
		return m.FrozenDetail
	}
	return nil
}

func (m *FrozenAssetsTable) GetThawDetail() map[string]*FrozenDetails {
	if m != nil {
		return m.ThawDetail
	}
	return nil
}

func (m *FrozenAssetsTable) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type FrozenDetails struct {
	// string txid = 1;
	Height               int64    `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	Amount               string   `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Timestamp            int64    `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FrozenDetails) Reset()         { *m = FrozenDetails{} }
func (m *FrozenDetails) String() string { return proto.CompactTextString(m) }
func (*FrozenDetails) ProtoMessage()    {}
func (*FrozenDetails) Descriptor() ([]byte, []int) {
	return fileDescriptor_98cf7ef12ed80c79, []int{5}
}

func (m *FrozenDetails) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FrozenDetails.Unmarshal(m, b)
}
func (m *FrozenDetails) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FrozenDetails.Marshal(b, m, deterministic)
}
func (m *FrozenDetails) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FrozenDetails.Merge(m, src)
}
func (m *FrozenDetails) XXX_Size() int {
	return xxx_messageInfo_FrozenDetails.Size(m)
}
func (m *FrozenDetails) XXX_DiscardUnknown() {
	xxx_messageInfo_FrozenDetails.DiscardUnknown(m)
}

var xxx_messageInfo_FrozenDetails proto.InternalMessageInfo

func (m *FrozenDetails) GetHeight() int64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *FrozenDetails) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

func (m *FrozenDetails) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type NodeDetails struct {
	NodeDetail           []*NodeDetail `protobuf:"bytes,1,rep,name=node_detail,json=nodeDetail,proto3" json:"node_detail,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *NodeDetails) Reset()         { *m = NodeDetails{} }
func (m *NodeDetails) String() string { return proto.CompactTextString(m) }
func (*NodeDetails) ProtoMessage()    {}
func (*NodeDetails) Descriptor() ([]byte, []int) {
	return fileDescriptor_98cf7ef12ed80c79, []int{6}
}

func (m *NodeDetails) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeDetails.Unmarshal(m, b)
}
func (m *NodeDetails) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeDetails.Marshal(b, m, deterministic)
}
func (m *NodeDetails) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeDetails.Merge(m, src)
}
func (m *NodeDetails) XXX_Size() int {
	return xxx_messageInfo_NodeDetails.Size(m)
}
func (m *NodeDetails) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeDetails.DiscardUnknown(m)
}

var xxx_messageInfo_NodeDetails proto.InternalMessageInfo

func (m *NodeDetails) GetNodeDetail() []*NodeDetail {
	if m != nil {
		return m.NodeDetail
	}
	return nil
}

type NodeDetail struct {
	Address                 string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Height               int64    `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	Amount               string   `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NodeDetail) Reset()         { *m = NodeDetail{} }
func (m *NodeDetail) String() string { return proto.CompactTextString(m) }
func (*NodeDetail) ProtoMessage()    {}
func (*NodeDetail) Descriptor() ([]byte, []int) {
	return fileDescriptor_98cf7ef12ed80c79, []int{7}
}

func (m *NodeDetail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeDetail.Unmarshal(m, b)
}
func (m *NodeDetail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeDetail.Marshal(b, m, deterministic)
}
func (m *NodeDetail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeDetail.Merge(m, src)
}
func (m *NodeDetail) XXX_Size() int {
	return xxx_messageInfo_NodeDetail.Size(m)
}
func (m *NodeDetail) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeDetail.DiscardUnknown(m)
}

var xxx_messageInfo_NodeDetail proto.InternalMessageInfo

func (m *NodeDetail) GetTxid() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *NodeDetail) GetHeight() int64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *NodeDetail) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

//节点待解冻的信息
type NodeTable struct {
	NodeDetails          map[int64]*NodeDetails `protobuf:"bytes,1,rep,name=node_details,json=nodeDetails,proto3" json:"node_details,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *NodeTable) Reset()         { *m = NodeTable{} }
func (m *NodeTable) String() string { return proto.CompactTextString(m) }
func (*NodeTable) ProtoMessage()    {}
func (*NodeTable) Descriptor() ([]byte, []int) {
	return fileDescriptor_98cf7ef12ed80c79, []int{8}
}

func (m *NodeTable) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeTable.Unmarshal(m, b)
}
func (m *NodeTable) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeTable.Marshal(b, m, deterministic)
}
func (m *NodeTable) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeTable.Merge(m, src)
}
func (m *NodeTable) XXX_Size() int {
	return xxx_messageInfo_NodeTable.Size(m)
}
func (m *NodeTable) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeTable.DiscardUnknown(m)
}

var xxx_messageInfo_NodeTable proto.InternalMessageInfo

func (m *NodeTable) GetNodeDetails() map[int64]*NodeDetails {
	if m != nil {
		return m.NodeDetails
	}
	return nil
}

func init() {
	proto.RegisterEnum("protos.ProposalStatus", ProposalStatus_name, ProposalStatus_value)
	proto.RegisterType((*GovernTokenBalance)(nil), "protos.GovernTokenBalance")
	proto.RegisterType((*TriggerDesc)(nil), "protos.TriggerDesc")
	proto.RegisterMapType((map[string][]byte)(nil), "protos.TriggerDesc.ArgsEntry")
	proto.RegisterType((*Proposal)(nil), "protos.Proposal")
	proto.RegisterMapType((map[string][]byte)(nil), "protos.Proposal.ArgsEntry")
	proto.RegisterType((*ProposalRatio)(nil), "protos.ProposalRatio")
	proto.RegisterMapType((map[string]int64)(nil), "protos.ProposalRatio.UserRatioEntry")
	proto.RegisterType((*FrozenAssetsTable)(nil), "protos.FrozenAssetsTable")
	proto.RegisterMapType((map[string]*FrozenDetails)(nil), "protos.FrozenAssetsTable.FrozenDetailEntry")
	proto.RegisterMapType((map[string]*FrozenDetails)(nil), "protos.FrozenAssetsTable.ThawDetailEntry")
	proto.RegisterType((*FrozenDetails)(nil), "protos.FrozenDetails")
	proto.RegisterType((*NodeDetails)(nil), "protos.NodeDetails")
	proto.RegisterType((*NodeDetail)(nil), "protos.NodeDetail")
	proto.RegisterType((*NodeTable)(nil), "protos.NodeTable")
	proto.RegisterMapType((map[int64]*NodeDetails)(nil), "protos.NodeTable.NodeDetailsEntry")
}

func init() { proto.RegisterFile("protos/proposal.proto", fileDescriptor_98cf7ef12ed80c79) }

var fileDescriptor_98cf7ef12ed80c79 = []byte{
	// 782 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x95, 0xdd, 0x4e, 0xe3, 0x46,
	0x14, 0xc7, 0x6b, 0x3b, 0x04, 0x72, 0x9c, 0xd0, 0x74, 0x28, 0xc8, 0x0a, 0xfd, 0x40, 0x6e, 0x55,
	0x85, 0xa2, 0x06, 0x35, 0x5c, 0x50, 0x55, 0xed, 0x45, 0x48, 0x02, 0xa2, 0x42, 0x14, 0x39, 0x81,
	0x8b, 0x4a, 0x55, 0x34, 0x89, 0x87, 0xc4, 0xc2, 0xf1, 0x44, 0x33, 0xe3, 0x00, 0x7d, 0x8c, 0xf6,
	0x21, 0xfa, 0x04, 0xbd, 0xae, 0xf6, 0xcd, 0x56, 0x9e, 0x19, 0x27, 0x8e, 0x09, 0xbb, 0xd2, 0x6a,
	0xef, 0xe6, 0x9c, 0xf9, 0x9f, 0x33, 0xbf, 0xf3, 0xe1, 0x04, 0x76, 0x67, 0x8c, 0x0a, 0xca, 0x8f,
	0x67, 0x8c, 0xce, 0x28, 0xc7, 0x61, 0x43, 0xda, 0xa8, 0xa8, 0xdc, 0xee, 0x7f, 0x26, 0xa0, 0x0b,
	0x3a, 0x27, 0x2c, 0xea, 0xd3, 0x07, 0x12, 0x9d, 0xe1, 0x10, 0x47, 0x23, 0x82, 0xbe, 0x81, 0x8a,
	0xa0, 0x02, 0x87, 0x83, 0xa1, 0x72, 0x38, 0xc6, 0x81, 0x51, 0x2f, 0x79, 0x65, 0xe9, 0x4c, 0x45,
	0xbf, 0xc2, 0x3e, 0x9e, 0xe3, 0x20, 0xc4, 0xc3, 0x90, 0xa4, 0xc2, 0xc1, 0x3d, 0x65, 0x03, 0xe1,
	0xcf, 0x28, 0x77, 0x4c, 0x19, 0xe2, 0x2c, 0x24, 0x3a, 0xec, 0x9c, 0xb2, 0x7e, 0x72, 0x8f, 0x4e,
	0xc1, 0x09, 0xe9, 0xe8, 0x81, 0xf8, 0x6b, 0x62, 0x2d, 0x19, 0xbb, 0xab, 0xee, 0xf3, 0x81, 0x6d,
	0xf8, 0x6a, 0xfd, 0xbb, 0x69, 0x8d, 0x4e, 0x41, 0x86, 0xef, 0xaf, 0x79, 0xfa, 0x46, 0x4b, 0x12,
	0xf8, 0x35, 0xaf, 0x2f, 0x32, 0x6c, 0x28, 0xf8, 0x3c, 0x40, 0x1a, 0xee, 0xbe, 0x31, 0xc0, 0xee,
	0xb3, 0x60, 0x3c, 0x26, 0xac, 0x43, 0xf8, 0x08, 0xed, 0x41, 0x71, 0x42, 0x82, 0xf1, 0x44, 0xc8,
	0x4e, 0x59, 0x9e, 0xb6, 0x12, 0xff, 0x94, 0xfa, 0x71, 0x48, 0x74, 0x3b, 0xb4, 0x25, 0xfd, 0x44,
	0x4c, 0xa8, 0xaf, 0x4b, 0xd5, 0x16, 0xfa, 0x11, 0x0a, 0x98, 0x8d, 0xb9, 0x53, 0x38, 0xb0, 0xea,
	0x76, 0xf3, 0x4b, 0x35, 0x2d, 0xde, 0xc8, 0x3c, 0xd5, 0x68, 0xb1, 0x31, 0xef, 0x46, 0x82, 0x3d,
	0x7b, 0x52, 0x5a, 0x3b, 0x85, 0xd2, 0xc2, 0x85, 0xaa, 0x60, 0x3d, 0x90, 0x67, 0x3d, 0xae, 0xe4,
	0x88, 0x3e, 0x87, 0x8d, 0x39, 0x0e, 0x63, 0x05, 0x50, 0xf6, 0x94, 0xf1, 0xb3, 0xf9, 0x93, 0xe1,
	0xfe, 0x6f, 0xc2, 0xd6, 0xa2, 0x1f, 0x4b, 0x50, 0xe3, 0x15, 0x50, 0x73, 0x05, 0xb4, 0xa1, 0x41,
	0x2d, 0x09, 0x5a, 0x4b, 0x41, 0xd3, 0x7c, 0x79, 0x4a, 0xf4, 0x03, 0x6c, 0x0a, 0x55, 0x84, 0x9c,
	0x8e, 0xdd, 0xdc, 0x59, 0x53, 0x9b, 0x97, 0x6a, 0xd0, 0xd7, 0x60, 0xcf, 0xa9, 0x20, 0x03, 0x3c,
	0xa5, 0x71, 0x24, 0xf4, 0x38, 0x20, 0x71, 0xb5, 0xa4, 0x07, 0x35, 0xa0, 0xc8, 0x05, 0x16, 0x31,
	0x77, 0x8a, 0x07, 0x46, 0x7d, 0xbb, 0xb9, 0x97, 0x27, 0xe8, 0xc9, 0x5b, 0x4f, 0xab, 0x50, 0x0d,
	0xb6, 0xd4, 0x70, 0x09, 0x73, 0x36, 0x65, 0xb6, 0x85, 0xfd, 0xe1, 0x1d, 0xfc, 0xdb, 0x80, 0x4a,
	0xfa, 0x9e, 0x87, 0x45, 0x40, 0x51, 0x1b, 0x20, 0xe6, 0x84, 0x0d, 0x58, 0x62, 0x39, 0x86, 0x6c,
	0xce, 0xb7, 0x79, 0x34, 0x29, 0x6d, 0xdc, 0x72, 0xc2, 0xe4, 0x49, 0xb5, 0xa9, 0x14, 0xa7, 0x76,
	0xed, 0x17, 0xd8, 0x5e, 0xbd, 0x7c, 0x1f, 0x94, 0x95, 0x85, 0xfa, 0xc7, 0x82, 0xcf, 0xce, 0x19,
	0xfd, 0x8b, 0x44, 0x2d, 0xce, 0x89, 0xe0, 0xfd, 0xe4, 0x0b, 0x48, 0xf4, 0xf2, 0xe3, 0xd5, 0x39,
	0x94, 0x81, 0x6e, 0xa0, 0x72, 0x2f, 0xa5, 0x03, 0x9f, 0x08, 0x1c, 0x84, 0x8e, 0x29, 0x89, 0x8f,
	0x52, 0xe2, 0x17, 0x79, 0xb4, 0xa7, 0x23, 0xd5, 0x0a, 0xbc, 0x7c, 0x9f, 0x71, 0xa1, 0xdf, 0xc0,
	0x16, 0x13, 0xfc, 0x98, 0xe6, 0x53, 0xeb, 0x71, 0xf8, 0x7a, 0xbe, 0xfe, 0x04, 0x3f, 0x66, 0xb3,
	0x81, 0x58, 0x38, 0xd0, 0x17, 0x50, 0x12, 0xc1, 0x94, 0x70, 0x81, 0xa7, 0x33, 0xb9, 0x35, 0x96,
	0xb7, 0x74, 0xd4, 0xee, 0xd2, 0x32, 0x33, 0xe1, 0x6b, 0x1a, 0x75, 0x94, 0x6d, 0x94, 0xdd, 0xdc,
	0x5d, 0x45, 0x51, 0xb1, 0x3c, 0xd3, 0xbf, 0x5a, 0x1f, 0x3e, 0xcd, 0x41, 0x7d, 0x84, 0xac, 0xee,
	0x9f, 0x50, 0x59, 0xb9, 0x7b, 0xd7, 0x2f, 0x86, 0x5e, 0x7a, 0xfd, 0xc1, 0x29, 0x6b, 0xb5, 0x19,
	0x56, 0xae, 0x19, 0xee, 0x19, 0xd8, 0xd7, 0xd4, 0x27, 0x69, 0xf2, 0x13, 0xb0, 0x23, 0xea, 0x93,
	0x74, 0x0a, 0x6a, 0x0f, 0x51, 0x0a, 0xb9, 0x54, 0x7a, 0x10, 0x2d, 0xce, 0xee, 0x0d, 0xc0, 0xf2,
	0x06, 0x21, 0x28, 0x88, 0xa7, 0xc0, 0xd7, 0x45, 0xcb, 0x73, 0x86, 0xd9, 0x7c, 0x85, 0xd9, 0xca,
	0x32, 0xbb, 0xff, 0x1a, 0x50, 0x4a, 0x52, 0xaa, 0x15, 0xec, 0x42, 0x39, 0x03, 0xc5, 0x35, 0x95,
	0x9b, 0xa5, 0x52, 0x3b, 0x91, 0xa9, 0x44, 0x2d, 0x85, 0xbd, 0xa4, 0xe4, 0xb5, 0x1e, 0x54, 0xf3,
	0x82, 0xec, 0x80, 0x2c, 0x35, 0xa0, 0xc3, 0xd5, 0x01, 0xed, 0xbc, 0xac, 0x3d, 0x3b, 0x9e, 0xef,
	0x3b, 0xb0, 0xbd, 0xfa, 0xc3, 0x81, 0x00, 0x8a, 0x77, 0xbf, 0xf7, 0x2f, 0xaf, 0x2f, 0xaa, 0x9f,
	0x20, 0x1b, 0x36, 0x7b, 0xb7, 0xed, 0x76, 0xb7, 0xd7, 0xab, 0x1a, 0x89, 0x71, 0xde, 0xba, 0xbc,
	0xba, 0xf5, 0xba, 0x55, 0x13, 0x95, 0x61, 0xab, 0xdd, 0xba, 0x6e, 0x77, 0xaf, 0xba, 0x9d, 0xaa,
	0x75, 0x56, 0xff, 0xe3, 0xbb, 0x71, 0x20, 0x26, 0xf1, 0xb0, 0x31, 0xa2, 0xd3, 0xe3, 0xa7, 0x78,
	0x46, 0xd8, 0x68, 0x82, 0x83, 0x48, 0x1f, 0x29, 0x23, 0xc7, 0x0a, 0x63, 0xa8, 0xfe, 0x7f, 0x4f,
	0xde, 0x06, 0x00, 0x00, 0xff, 0xff, 0xc5, 0x72, 0x6f, 0xb4, 0x9f, 0x07, 0x00, 0x00,
}
